-- begin GURU_SESSION
alter table GURU_SESSION add constraint FK_GURU_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references GURU_SPEAKER(ID)^
create index IDX_GURU_SESSION_ON_SPEAKER on GURU_SESSION (SPEAKER_ID)^
-- end GURU_SESSION
-- begin GURU_SPEAKER
create index IDX_GURU_SPEAKER_SURNAME on GURU_SPEAKER (SPEAKER_SURNAME)^
-- end GURU_SPEAKER
