alter table GURU_WEEK add constraint FK_GURU_WEEK_ON_EDUCATIONAL_YEAR foreign key (EDUCATIONAL_YEAR_ID) references GURU_EDUCATIONAL_YEAR(ID);
create index IDX_GURU_WEEK_ON_EDUCATIONAL_YEAR on GURU_WEEK (EDUCATIONAL_YEAR_ID);
