alter table GURU_LESSON add constraint FK_GURU_LESSON_ON_PLANNING_ITEM foreign key (PLANNING_ITEM_ID) references GURU_LESSONS_PLANNING_ITEM(ID);
create index IDX_GURU_LESSON_ON_PLANNING_ITEM on GURU_LESSON (PLANNING_ITEM_ID);
