alter table GURU_ROOM add constraint FK_GURU_ROOM_ON_EDUCTAIONAL_ORGANIZATION foreign key (EDUCTAIONAL_ORGANIZATION_ID) references GURU_SCHOOL(ID);
create index IDX_GURU_ROOM_ON_EDUCTAIONAL_ORGANIZATION on GURU_ROOM (EDUCTAIONAL_ORGANIZATION_ID);
