alter table GURU_LESSONS_GRID add constraint FK_GURU_LESSONS_GRID_ON_ORGANIZATION foreign key (ORGANIZATION_ID) references GURU_SCHOOL(ID);
create index IDX_GURU_LESSONS_GRID_ON_ORGANIZATION on GURU_LESSONS_GRID (ORGANIZATION_ID);
