alter table GURU_LESSON add constraint FK_GURU_LESSON_ON_GROUP_ON_THE_FLY foreign key (GROUP_ON_THE_FLY_ID) references GURU_GROUP_FOR_LESSON(ID);
create index IDX_GURU_LESSON_ON_GROUP_ON_THE_FLY on GURU_LESSON (GROUP_ON_THE_FLY_ID);
