alter table GURU_GROUP_FOR_LESSON add constraint FK_GURU_GROUP_FOR_LESSON_ON_SCHOOL_CLASS foreign key (SCHOOL_CLASS_ID) references GURU_SCHOOL_CLASS(ID);
alter table GURU_GROUP_FOR_LESSON add constraint FK_GURU_GROUP_FOR_LESSON_ON_SUBJECT foreign key (SUBJECT_ID) references GURU_SUBJECT(ID);
alter table GURU_GROUP_FOR_LESSON add constraint FK_GURU_GROUP_FOR_LESSON_ON_TEACHER foreign key (TEACHER_ID) references GURU_TEACHER(ID);
create index IDX_GURU_GROUP_FOR_LESSON_ON_SCHOOL_CLASS on GURU_GROUP_FOR_LESSON (SCHOOL_CLASS_ID);
create index IDX_GURU_GROUP_FOR_LESSON_ON_SUBJECT on GURU_GROUP_FOR_LESSON (SUBJECT_ID);
create index IDX_GURU_GROUP_FOR_LESSON_ON_TEACHER on GURU_GROUP_FOR_LESSON (TEACHER_ID);
