alter table GURU_TEACHER add constraint FK_GURU_TEACHER_ON_ORGANIZATION foreign key (ORGANIZATION_ID) references GURU_SCHOOL(ID);
create index IDX_GURU_TEACHER_ON_ORGANIZATION on GURU_TEACHER (ORGANIZATION_ID);
