alter table GURU_SUBJECT add constraint FK_GURU_SUBJECT_ON_PARENT_SUBJECT foreign key (PARENT_SUBJECT_ID) references GURU_SUBJECT(ID);
create index IDX_GURU_SUBJECT_ON_PARENT_SUBJECT on GURU_SUBJECT (PARENT_SUBJECT_ID);
