alter table GURU_SCHOOL add constraint FK_GURU_SCHOOL_ON_PARENT_ORGANIZATION foreign key (PARENT_ORGANIZATION_ID) references GURU_SCHOOL(ID);
create index IDX_GURU_SCHOOL_ON_PARENT_ORGANIZATION on GURU_SCHOOL (PARENT_ORGANIZATION_ID);
