alter table GURU_LESSON add constraint FK_GURU_LESSON_ON_STUDY_GROUP foreign key (STUDY_GROUP_ID) references GURU_GROUP_FOR_LESSON(ID);
alter table GURU_LESSON add constraint FK_GURU_LESSON_ON_SUBJECT foreign key (SUBJECT_ID) references GURU_LESSONS_PLANNING_ITEM(ID);
alter table GURU_LESSON add constraint FK_GURU_LESSON_ON_TEACHER foreign key (TEACHER_ID) references GURU_TEACHER(ID);
create index IDX_GURU_LESSON_ON_STUDY_GROUP on GURU_LESSON (STUDY_GROUP_ID);
create index IDX_GURU_LESSON_ON_SUBJECT on GURU_LESSON (SUBJECT_ID);
create index IDX_GURU_LESSON_ON_TEACHER on GURU_LESSON (TEACHER_ID);
