alter table GURU_LESSONS_GRID_ITEM add constraint FK_GURU_LESSONS_GRID_ITEM_ON_GRID_TYPE foreign key (GRID_TYPE_ID) references GURU_LESSONS_GRID(ID);
create index IDX_GURU_LESSONS_GRID_ITEM_ON_GRID_TYPE on GURU_LESSONS_GRID_ITEM (GRID_TYPE_ID);
