alter table GURU_TIME_TABLE_TEMPLATE_ITEM add constraint FK_GURU_TIME_TABLE_TEMPLATE_ITEM_ON_ROOM foreign key (ROOM_ID) references GURU_ROOM(ID);
create index IDX_GURU_TIME_TABLE_TEMPLATE_ITEM_ON_ROOM on GURU_TIME_TABLE_TEMPLATE_ITEM (ROOM_ID);
