create table GURU_GROUPS_FOR_INDIVIDUAL_PLANNING_SCHOOL_CLASS_LINK (
    GROUPS_FOR_INDIVIDUAL_PLANNING_ID uuid,
    SCHOOL_CLASS_ID uuid,
    primary key (GROUPS_FOR_INDIVIDUAL_PLANNING_ID, SCHOOL_CLASS_ID)
);
