alter table GURU_LESSONS_PLANNING_ITEM add constraint FK_GURU_LESSONS_PLANNING_ITEM_ON_TEACHER foreign key (TEACHER_ID) references GURU_TEACHER(ID);
create index IDX_GURU_LESSONS_PLANNING_ITEM_ON_TEACHER on GURU_LESSONS_PLANNING_ITEM (TEACHER_ID);
