update GURU_LESSONS_PLANNING_ITEM set IS_INDIVIDUAL_PLAN_ITEM = false where IS_INDIVIDUAL_PLAN_ITEM is null ;
alter table GURU_LESSONS_PLANNING_ITEM alter column IS_INDIVIDUAL_PLAN_ITEM set not null ;
