alter table GURU_LESSONS_PLANNING_ITEM add constraint FK_GURU_LESSONS_PLANNING_ITEM_ON_SUBJECT foreign key (SUBJECT_ID) references GURU_SUBJECT(ID);
create index IDX_GURU_LESSONS_PLANNING_ITEM_ON_SUBJECT on GURU_LESSONS_PLANNING_ITEM (SUBJECT_ID);
