create table GURU_GROUP_FOR_INDIVIDUAL_PLANNING_SCHOOL_CLASS_LINK (
    GROUP_FOR_INDIVIDUAL_PLANNING_ID uuid,
    SCHOOL_CLASS_ID uuid,
    primary key (GROUP_FOR_INDIVIDUAL_PLANNING_ID, SCHOOL_CLASS_ID)
);
